### ISSUE TITLE
The hardcoding of loading configuration from a file is bad design

### ISSUE THREAD

**Issue by dalewking** [MarkNenadov/kYNAB#1]
The only way to create the YnabBrokerImpl is to pass it a YnabConfiguration and a YnabConfiguration is hardcoded to load its values from a Yaml with a hardcoded file name in the current directory (with no protection on the sensitive data it contains) and there is no way to change this since everything is final. This is a bad design (apparently you don't know about dependency injection)

This is what you should do:

- The getUrl and it's companion getEndpointPath should just move into YnabBrokerImpl. They were final anyway and could not be overridden so there is no point to them being in configuration.
- That leaves only 2 pieces of configuration data to pass to the Broker, the token and the base url.
- The YnabBrokerImpl constructor should just become:

     `class YnabBrokerImpl(private val accessToken:String, val baseUrl:String = "https://api.youneedabudget.com/v1")`
- YnabConfiguration should die a horrible, painful death for being the horrific design that it is.
- You can then lose the dependency on yaml

**Comment by MarkNenadov** [comment]
Hi Dale,

Thanks for your comments. I do agree that the design is pretty bad.

I'm actually familiar with dependency injection, inversion of control, etc. So I guess that makes it even less excusable.

Anyways, I appreciate you taking the time to comment on this and I hope to be able to work on this project some more shortly.

Have a good day,
~Mark

**Comment by dalewking** [comment]
Looks like you have implemented this so think it can be closed. Unfortunately, I discovered that you haven't implemented creating transactions so this does not help me.
